### ISSUE TITLE
Issue with EST on C) field

### ISSUE THREAD

**Issue by jj-sm** [slavak/PyNotam#7]
Test case:
```
A2396/24 NOTAMR A1561/24
Q) SKED/QCDAS/IV/BO/AE/000/999/0442N07409W010
A) SKBO
B) 2410131424 C) 2501102359 EST
E) COM VIA DATA LINK U/S
```

Error code:
```
Traceback (most recent call last):
  File "****/NOTAM/PyNotam/test.py", line 8, in <module>
    w = notam.Notam.from_str(k)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "****/NOTAM/PyNotam/notam.py", line 79, in from_str
    visitor.parse(s)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/parsimonious/nodes.py", line 252, in parse
    return self._parse_or_match(text, pos, 'parse')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/parsimonious/nodes.py", line 287, in _parse_or_match
    return self.visit(getattr(self.grammar, method_name)(text, pos=pos))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/parsimonious/grammar.py", line 112, in parse
    return self.default_rule.parse(text, pos=pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/parsimonious/expressions.py", line 141, in parse
    node = self.match(text, pos=pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/parsimonious/expressions.py", line 158, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'e_clause' didn't match at 'EST
E) COM VIA DATA ' (line 4, column 29).
```

My Code:
```python
import notam

k = """(A2396/24 NOTAMR A1561/24
Q) SKED/QCDAS/IV/BO/AE/000/999/0442N07409W010
A) SKBO
B) 2410131424 C) 2501102359 EST
E) COM VIA DATA LINK U/S)"""
w = notam.Notam.from_str(k)

print(w.decoded())
```

**Comment by jj-sm** [comment]
Found the issue, not the solution. When it's `C) 2501102359 EST` the bug triggers, however  `C) 2501102359EST` doesn't

**Comment by jj-sm** [comment]
Solved on [https://github.com/slavak/PyNotam/pull/8](https://github.com/slavak/PyNotam/pull/8)
